spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001
  
spring:
  profiles: dev
  application:  
    name: microservicecloud-config-dept-client
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
        driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
        url: jdbc:mysql://localhost:3306/clouddb01              # 数据库名称
        username: root
        password: 123
        dbcp2:
          min-idle: 5                                           # 数据库连接池的最小维持连接数
          initial-size: 5                                       # 初始化连接数
          max-total: 5                                          # 最大连接数
          max-wait-millis: 200                                  # 等待连接获取的最大超时时间
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.gcc.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      #defaultZone: http://localhost:7001/eureka
       defaultZone: http://eureka7001.com:7001/eureka/  
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true     #访问路径可以显示I     

info: 
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$  
<<<<<<< HEAD

=======
  
>>>>>>> a5f29cc42e448914d40ce018d708f9dacefff2b7
---
server:
  port: 8001
  
spring:
  profiles: test
  application:  
    name: microservicecloud-config-dept-client
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
        driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
<<<<<<< HEAD
        url: jdbc:mysql://localhost:3306/clouddb02              # 数据库名称
=======
        url: jdbc:mysql://localhost:3306/clouddb03             # 数据库名称
>>>>>>> a5f29cc42e448914d40ce018d708f9dacefff2b7
        username: root
        password: 123
        dbcp2:
          min-idle: 5                                           # 数据库连接池的最小维持连接数
          initial-size: 5                                       # 初始化连接数
          max-total: 5                                          # 最大连接数
          max-wait-millis: 200                                  # 等待连接获取的最大超时时间
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.gcc.springcloud.entities    # 所有Entity别名类所在包
<<<<<<< HEAD
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
=======
  mapper-locations: classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
>>>>>>> a5f29cc42e448914d40ce018d708f9dacefff2b7

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      #defaultZone: http://localhost:7001/eureka
       defaultZone: http://eureka7001.com:7001/eureka/  
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true     #访问路径可以显示I     

info: 
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$  
<<<<<<< HEAD
  
=======
>>>>>>> a5f29cc42e448914d40ce018d708f9dacefff2b7
